version: "3.2"

services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mariadb_mg
    ports:
      - "3396:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
    environment:
      -  MYSQL_ROOT_PASSWORD=your_root_password
    restart: always
  
  phpmyadmin:
    depends_on: 
      - db  
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mg
    environment:
     - PMA_HOST=db
    restart: always
    ports:
     - 8081:80
    volumes:
     - ./sessions
